-- AlterTable
ALTER TABLE "Person" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "Person" ADD COLUMN IF NOT EXISTS "gender" TEXT;
ALTER TABLE "Person" ADD COLUMN IF NOT EXISTS "preferences" JSONB DEFAULT '[]';
ALTER TABLE "Person" ADD COLUMN IF NOT EXISTS "context" TEXT;
