// Prisma client types are generated by `prisma generate`; until then, this
// import may resolve without types. The rest of the codebase treats the
// client as loosely typed.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore prisma client is generated at build time
import { PrismaClient } from "@prisma/client";

/**
 * Singleton PrismaClient. In dev, tsx watch may reload frequently, so we cache
 * the client on globalThis to avoid exhausting the connection pool.
 */
const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma: PrismaClient =
  globalForPrisma.prisma ?? new PrismaClient();

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}
